### ISSUE TITLE
Use Spotify's own API for album cover when listening to Spotify

### ISSUE THREAD

**Issue by vanshady** [Pe8er/Playbox.widget#14]
https://developer.spotify.com/web-api/get-album/

**Comment by noiis** [comment]
Please, at least let that option available to user to choose. 
Half of my albums are not currently available by the currently last.ft API.

**Comment by Pe8er** [comment]
Hey guys,

Sorry for the late reply. I've just implemented this change: Spotify songs will now get artwork from Spotify API. Please test and let me know if you see anything odd.

https://github.com/Pe8er/Playbox.widget/raw/master/Playbox.widget.zip

**Comment by noiis** [comment]
@Pe8er Played a bunch of tracks, getting all albums covers now. Thanks!
