### ISSUE TITLE
As of yesterday Spotify covert api was working, now its a 401 http error

### ISSUE THREAD

**Issue by ACPixel** [Pe8er/Playbox.widget#16]
title should say it all, but as of, I guess today, you need an api key for Spotify api...

**Comment by Pe8er** [comment]
Bummer. I guess I'll go back to last.fm then.

**Comment by Pe8er** [comment]
Please check if it works for you now: https://github.com/Pe8er/Playbox.widget/blob/master/Playbox.widget.zip

**Comment by ACPixel** [comment]
yeah, changing it to lastfm is what I did and it started to work perfectly again :)
