### ISSUE TITLE
Doesn't work with Apple Music

### ISSUE THREAD

**Issue by samuelbrooks** [Pe8er/Playbox.widget#2]
It works great if you're playing from a local library but doesn't seem to work with Apples subscription service (show's a black bar instead). Although I think this is on Apple as last time I checked this was a limitation with their own service. 

Otherwise awesome script!

**Comment by fishbiscuit13** [comment]
Are you sure you also copied the other files in the "as" folder (default.png, Get Current Track.applescript, and songMeta.plist)? Because it's working for an Apple Music song for me right now.

**Comment by samuelbrooks** [comment]
Yea it's defiantly all in there. Weird, I must have something interfering with it. I just noticed the styling for the text also isn't right (when playing from local library). 

Here's some screens if you have any advice that would be awesome otherwise all good! :) 

http://imgur.com/a/TVbDA

**Comment by fishbiscuit13** [comment]
Well, the text just looks like that because it _isn't_ styled. Just put a "font-family whatever" in the .text section. And you're sure the as folder is in the same directory (and level) as index.coffee? Unless you've edited it, I can't see why it wouldn't work, it did right away for me.

**Comment by samuelbrooks** [comment]
Oh, haha. I didn't even check to actually see if it already had a preset font style. That's fine now :) 

Yea it defiantly is http://i.imgur.com/zE45Wwl.jpg. Your script would totally be fine, it's probably something else I have installed messing with it. Thanks anyway!

**Comment by Pe8er** [comment]
@samuelbrooks I'm sorry I can't help man, I don't use Apple Music. Although since it seems to work just fine for @fishbiscuit13, there must be something fishy going on. I did have an issue with text not being styled properly like on your screenshots and restarting Ubersicht helped. Let me know!

**Comment by samuelbrooks** [comment]
Not a problem man! It's defiantly something on my system. I tried restarting it but I ended up just putting my own font styles in and it did the trick. I'll post back if it turns out to be something else. 

Thanks for making such a clean widget by the way! You're the first developer I've seen to setup such an easy way to change positions.

**Comment by Pe8er** [comment]
> Thanks for making such a clean widget by the way! You're the first developer I've seen to setup such an easy way to change positions.

Haha thanks man, maybe that's because I'm not _really_ a developer 😬 This is a good day, it turns out there are good things about trying to code without having the right brain to code!
