### ISSUE TITLE
Widget stopped working (?)

### ISSUE THREAD

**Issue by pugson** [Pe8er/Playbox.widget#22]
Hey @Pe8er, looks like the latest Spotify update (`1.0.65.320.gac7a8e02`) might have broken the widget. It's not displaying on the desktop at all and there are no console errors.

I think it's an issue with `Get Current Track.applescript` — it's not producing any logs. I tried running it inside the _Script Editor.app_ and it was processing endlessly.

**Comment by pugson** [comment]
Oh, maybe I have a really old version. Let me grab the latest build first.

**Comment by pugson** [comment]
Ok I found the culprit. When cloning the repo in the Ubersicht widgets directory it was looking for the AppleScript in `/Playbox.widget/lib/Get Current Track.applescript` where in fact the right location was `Playbox.widget/Playbox.widget/lib/Get Current Track.applescript`.

**Comment by Pe8er** [comment]
![nevermind](https://media.giphy.com/media/e7Fdp0v1fZgti/giphy.gif)

**Comment by pugson** [comment]
¯\_(ツ)_/¯

**Comment by Pe8er** [comment]
Dobra robota 😄

**Comment by pugson** [comment]
Żeby nie było nie siedziałem nad tym 2 tygodnie haha
