### ISSUE TITLE
High Sierra 10.13: Tons of AppleEvent errors in system.log

### ISSUE THREAD

**Issue by borgendorf** [Pe8er/Playbox.widget#23]
Hi there - first let me tell you how much I enjoy this widget. It's one of many in my Sidebar stack. I'm trying to track down why my High Sierra system randomly freezes, and in looking through my system.log I noticed this message repeated constantly (21 times each time the script runs)

`osascript[5532]: AppleEvents: received mach msg which wasn't complex type as expected in getMemoryReference.`

I narrowed it down to the Playbox widget (I see these messages when Playbox is the only widget installed, and they go away when other widgets are running but Playbox is not).

Please let me know if there is something I can try to help debug. I see that the script has an option for logging but I'm not sure where those logs live.

**Comment by Pe8er** [comment]
I see the same messages in the console. It doesn't cause any freezes on my system though - guess I got lucky :) I found out that [other people noticed this bug too](https://forums.developer.apple.com/thread/88126) and seems like it is OS related. According to that discussion, it might be fixed in 10.3.1. Let's wait for it!

**Comment by borgendorf** [comment]
FYI 10.13.1 didn't fix the AppleScript message. Oh well. 🤷‍♂️

**Comment by Pe8er** [comment]
I just installed 10.3.2 Dev Beta (17C60c) and these error messages are gone! Can you try the dev beta @borgendorf?

**Comment by borgendorf** [comment]
I'm not on the developer releases, but I'm glad Apple fixed that bug. I'm confident it is not contributing to my freeze issues now, but fewer errors are always better. 😄
