### ISSUE TITLE
Show Playbox even when music is paused

### ISSUE THREAD

**Issue by destinationunknown** [Pe8er/Playbox.widget#26]
Currently the playbox disappears when I pause Spotify, even when I leave the app running. It would be nice to keep the window up even when music is paused. Perhaps you could write the song metadata to a local buffer and then update the view from that buffer as opposed to directly updating the view?

**Comment by Pe8er** [comment]
Hey!

The widget does save song metadata to a local buffer. If you'd like it to not hide when music is paused, you need to get rid of the following `if` statement in line 261 of index.coffee:

```
  if !output
    div.animate({opacity: 0}, 250, 'swing').hide(1)
  else
```

and then the following in line 279:

```
    div.show(1).animate({opacity: 1}, 250, 'swing')
```

And finally correct indentation on everything in between.

Hope this helps! I'm Sorry I'm asking you to do it manually but I no longer develop/support this widget.

**Comment by destinationunknown** [comment]
Thanks! Much appreciated.
