### ISSUE TITLE
/lib cache directory not pruned

### ISSUE THREAD

**Issue by singhpaul** [Pe8er/Playbox.widget#28]
Hi, thanks for writing such a useful plugin.

While cleaning up disk space recently we noticed that the plugin's /lib directory was using over 1GB of space. This is because the album covers are cached to disk but not pruned (or not pruned frequently enough). Not sure what the caching scheme is but we noticed that the file name enumeration went up to 999 starting at 0. So perhaps they are being pruned after reaching 1,000 but that seems excessive.

/Users/[username]/Library/Application Support/Übersicht/widgets/Playbox.widget/lib

Happy to help investigate.

**Comment by Pe8er** [comment]
Thank you for the report and suggestion! The script should delete old cover every time a new cover is extracted from iTunes…I just checked and the command I wrote was obviously broken.
