### ISSUE TITLE
Syntax error upon installation

### ISSUE THREAD

**Issue by seansellek** [Pe8er/Playbox.widget#3]
I'm receiving the following error when using Playbox:

`2077752445:1 SyntaxError: Unexpected identifier 'Object'. Expected either a closing ']' or a ',' following an array element.`

I haven't dove in very deep, but I'll try to find the cause of the issue today.

**Comment by Pe8er** [comment]
Thank you for the report. I found this issue sometime ago, but never felt like looking into it. Thanks for the kick :) I just pushed an update that fixes this problem. Check it out and let me know how it works for you.

**Comment by seansellek** [comment]
Nice! works well now
