### ISSUE TITLE
Default Font/No Font config?

### ISSUE THREAD

**Issue by lukellyk** [Pe8er/Playbox.widget#4]
<img width="204" alt="screen shot 2016-05-10 at 10 14 59 am" src="https://cloud.githubusercontent.com/assets/12542270/15131980/1495e58e-1698-11e6-9971-b140b13e589f.png">

I don't like this ugly font. How do I fix it?

**Comment by Pe8er** [comment]
@lukellyk thanks for reporting! What is your OS X version?

**Comment by lukellyk** [comment]
I have downloaded the latest version and it continues to display like this... I am running Yosemite

**Comment by Pe8er** [comment]
It might be an issue with Yosemite, although I can't test it myself, all my computers are running El Capitan. I'm sorry man, I can't help you.

**Comment by lukellyk** [comment]
I think it is due to yosemite lacking the 'San Francisco' font which you are using

**Comment by Pe8er** [comment]
I don't think so…I specified in CSS to use the system font, whatever that is on your OS:

`font-family system, -apple-system`

Looks like it doesn't work in Yosemite. I've just added a Helvetica Neue fallback - download the newest version and see if it works for you.
