### ISSUE TITLE
"Missing art" icon flickers every refresh, backdrop filter not working

### ISSUE THREAD

**Issue by katacarbix** [Pe8er/Playbox.widget#5]
I guess this is 2 issues in one. First, every second (when the widget refreshes) the missing art icon with the music note flickers black. This doesn't happen when there's artwork found for the current song. Secondly, the `-webkit-backdrop-filter` property doesn't work for me. It works in Safari, but not when the widget is displayed.

**Comment by Pe8er** [comment]
Thanks for the report. Which version of OS and Ubersicht are you on?

**Comment by katacarbix** [comment]
OS X 10.10.5, Übersicht 0.9 (39)

**Comment by Pe8er** [comment]
OK, let's try a couple things:

1. Please update to 0.9 (40).
2. Open debug console and see if it's showing any errors for the widget.

**Comment by katacarbix** [comment]
Ok so I think I found what's going on with the image. Upon looking in the images path of the resources section, I noticed that it loads the default art image from the file every refresh cycle and adds it to the pile of resources. Still unsure about the `backdrop-filter` property, though it's probably finicky as it's experimental.

**Comment by Pe8er** [comment]
Good observation! I think I managed to change the code so it doesn't load that image on every refresh. Download the latest version to check it out.

Regarding `backdrop-filter` property — yeah, it is quite erratic at times. Guess we have to live with it for now.
