### ISSUE TITLE
Don't hide Playbox when a track is paused

### ISSUE THREAD

**Issue by dubstrike** [Pe8er/Playbox.widget#8]
I sometimes pause my music for a long time and forget what I was listening to. It would be great if the widget did not disappear when the `track progress > 0%`.

**Comment by dubstrike** [comment]
#### Sidenote:

Loving your widgets, @Pe8er! Great job. 👏  I'm a bit sad about the `border-radius` and `-webkit-backdrop-filter` overflow bug in WebKit, but that's minor.

I modified the widget to snap to the bottom corner and it sits there nicely below my windows. Too bad there is no way to disable transparency without it affecting the dock and menubar. It would look much better.

![mod](http://d.pr/i/12KFX+)

**Comment by Pe8er** [comment]
Thanks for feedback! If you want the widget to not hide when music is paused, as you probably already figured out, you need to remove this if block, starting in line 167:

`if output.length == 0`

> I modified the widget to snap to the bottom corner and it sits there nicely below my windows.

My bad, sorry. I've updated the widget and now it positions correctly when you set `stickInCorner` to `true`.

> Too bad there is no way to disable transparency without it affecting the dock and menubar. It would look much better.

What do you mean by 'disable transparency'?

**Comment by dubstrike** [comment]
Yes, I've figured that out later. It's how Bowtie behaved and I found it useful. 

I meant transparency in OS X.
