### ISSUE TITLE
No Playbox visible, „[Error] Failed to load resource“

### ISSUE THREAD

**Issue by kbecker87** [Pe8er/Playbox.widget#9]
Hi! 

Playbox does not show up for me (the applescipt works fine). Übersicht Console show the following:

```
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (run, line 0)

[Error] Playbox-widget-index-coffee:
redraw (client.js:6:15819)
(anonymous function) (client.js:6:14620)
(anonymous function) (client.js:6:26619)
callback (client.js:6:9076)
(anonymous function) (client.js:6:4581)
emit (client.js:1:3389)
onreadystatechange (client.js:6:10068)
```

Any Idea why it does not work?

![](http://i.imgur.com/tjZnWbn.png)

**Comment by Pe8er** [comment]
Hmmm, I'm not sure what is happening here. Let's troubleshoot.

1. Do you have the newest Ubersicht version? It's 1.0(42)
2. Which OS X are you on?
3. Can you paste the output from the Applescript here please?

**Comment by kbecker87** [comment]
1. I’m using the newest beta by Felix (see [here)](https://github.com/felixhageloh/uebersicht/issues/217)
2. I’m on 10.11.6 final
3. That’d be 

`"DJ Shadow ~ Midnight In A Perfect World (Warrior Mix) ~ The Ultimate Collection ~ 1.56,.029.006.958.008 ~ 7,.638.999.938.965 ~ http://img2-ak.lst.fm/i/u/300x300/a3861591ee054c6699a6bf8a4920ed43.png"`

Thanks for looking into the issue!

**Comment by Pe8er** [comment]
Got it. The problem lies with the AppleScript. I'll get back to you with a fix.

**Comment by kbecker87** [comment]
Hi Piotr,

did you have time to look into the issue? Can you explain why it does work for most but not in my case? I’m eager to know whats different with my setup 😉

Greetings,
Karl

**Comment by Pe8er** [comment]
Hey man, I'm sorry I got caught up with work. I haven't finished fixing it yet. I know what's wrong though! Thanks for the kick, I'll try to get it done ASAP.

**Comment by Pe8er** [comment]
@kbecker87 can you please tell me what do you have set in:

- System Preferences > Language & Region >
  - Region
  - Advanced > Number Separators

**Comment by kbecker87** [comment]
Hi @Pe8er, my Region is `Germany (Custom)` and my number separators are:

* Grouping: `.` 
* Decimal: `,`

**Comment by Alutun** [comment]
Same issue here =) can give information if can help

**Comment by Pe8er** [comment]
Thanks guys. I know how to fix it, I just need to find some spare time. Please bear with me!

**Comment by kbecker87** [comment]
Hi there! I just wanted to check if there is something new to this issue =)

**Comment by ezadoo** [comment]
Have you found a fix for this issue? Or is there a bigger problem?

**Comment by wcolemorris** [comment]
Also checking in for an update to this issue!  Would love to switch back to this if you can fix the lack of appearance for iTunes.

Running Sierra

**Comment by wcolemorris** [comment]
Hey everybody, wanted to provide a fix that helped me.

After digging around with Dion and his Now Playing widget, I found that the included AppleScript was hanging because it couldn't find Spotify on my machine (I only had iTunes installed).

Try installing Spotify for desktop and then reloading Ubersicht.  These widgets pull from each but it seems as of right now installation isn't optional, only which is running.

Please patch this whenever you are able Pe8er!  Really appreciate the work you've done

**Comment by wcolemorris** [comment]
Hey Pe8er,

Is there a way to pass that duration value to the delay command so the info persists for the length of the song?

I'd love to have the delay last the length of the song minus say 500ms for a fade out and then start over with the fade in when the song switches.

Unfortunately seems like values[3] isn't initialized until after that delay command.

**Comment by kbecker87** [comment]
Hi @wcolemorris, thanks for your suggestion. I wanted to let you know that installing spotify unfortunately didn´t solve the problem for me.

**Comment by Pe8er** [comment]
Hey guys,

Sorry for the silence. I'm aware that absence of Spotify creates an issue, but unfortunately I haven't been able to find an elegant solution to it yet.

@wcolemorris I like the song duration - delay idea. I'll look into it.

**Comment by Pe8er** [comment]
Progress bar issue _might have been_ fixed. Please test:

https://github.com/Pe8er/Playbox.widget/raw/master/Playbox.widget.zip

**Comment by kbecker87** [comment]
After installing Spotify and using the new version Pe8er posted above I’m getting another error and no playbox widget showing up:

```
[Error] Playbox-widget-index-coffee:
"2017-05-24 12:00:58.548 osascript[41610:605591] ApplePersistence=NO
Retro Stefson @ Planetarium @ Kimbabwe @ 227 @ 94 @ /Playbox.widget/lib/cover712.jpg @ false @ false
"
	redraw (client.js:6:15819)
	(anonymous function) (client.js:6:14620)
	(anonymous function) (client.js:6:26901)
	callback (client.js:6:9076)
	(anonymous function) (client.js:6:4581)
	emit (client.js:1:3389)
	onreadystatechange (client.js:6:10068)
```

**Comment by Pe8er** [comment]
@kbecker87 it seems like your problem is not related to the progress bar or Spotify being installed… I'm afraid it's beyond my capabilities. @felixhageloh could you please take a peek?

**Comment by felixhageloh** [comment]
Are there more details on the error - like when  running the command / apple script separately in the terminal?
It is hard for me to test because I don't have spotify

**Comment by kbecker87** [comment]
The Applescipt seems to work fine:
 
![05-29-2017-21 47 06](https://cloud.githubusercontent.com/assets/8436596/26560766/4e561c08-44b9-11e7-9e4c-668b7ae762fe.jpg)

I think I’m having the same issue as in my first post a while ago:

![05-29-2017-21 51 54](https://cloud.githubusercontent.com/assets/8436596/26560781/6fc033f6-44b9-11e7-9e79-f57593e7ffb7.jpg)

**Comment by felixhageloh** [comment]
@kbecker87 do get the same output if you run the script from the terminal (using `osascript 'Get Current Track.applescript'`)?

**Comment by kbecker87** [comment]
The Cover Image does not load if I run the applescript from terminal:

![05-30-2017-09 16 56](https://cloud.githubusercontent.com/assets/8436596/26572104/f124c704-4518-11e7-8cb2-e37185f722fa.jpg)

**Comment by kbecker87** [comment]
@Pe8er I tried with a lot of different songs and checked the image url – they all work but I still dont get the widget to show.

![05-31-2017-15 03 20](https://cloud.githubusercontent.com/assets/8436596/26633100/8cd29baa-4612-11e7-985c-0ac3b25b15ca.jpg)
![05-31-2017-15 03 56](https://cloud.githubusercontent.com/assets/8436596/26633104/8f7ba1b2-4612-11e7-9774-52b3d68d19a5.jpg)

**Comment by kbecker87** [comment]
It’s `0`

![05-31-2017-15 48 57](https://cloud.githubusercontent.com/assets/8436596/26635018/ae737800-4618-11e7-88be-a4a8c003ca2b.jpg)

**Comment by felixhageloh** [comment]
Ok, so the command runs without error. However, it might be writing something to stderr, which Übersicht will also treat as an error (it could be the `ApplePersistence=NO` bit). 

One way to check would be to append ` 2> /dev/null` to the command and see if that fixes the error:

```coffeescript
command: "osascript 'Get Current Track.applescript' 2> /dev/null" 
```

**Comment by kbecker87** [comment]
Unfortunately appending `2> /dev/null` does not fix the error. Using the command in Terminal:

    [Playbox.widget] osascript 'Track.applescript' 2> /dev/null                                  master  ✱
    Christian Scott aTunde Adjuah @ The Reckoning @ Ruler Rebel @ 196 @ 120 @ https://lastfm-img2.akamaized.net/i/u/300x300/67171e721b1df2fd6edfd829851a5793.png @ false @ false

**Comment by felixhageloh** [comment]
I didn't have time to look into it deeper. It could be that redirecting stderr (`2> /dev/null`) does not work in this case. 

I am pretty sure that stderr output is the problem here. Is there any part of the AppleScript that logs to stderr?

**Comment by Pe8er** [comment]
@felixhageloh not that I know of. All AppleScript spits out is a string such as this:

```
"Genesis P-Orridge & Astrid Monroe @ The Final Puzzle @ When I Was Young @ 256 @ 8 @ /scripts/Media/cover517.jpg @ true @ false"

**Comment by Pe8er** [comment]
@kbecker87 do you still have this problem?

**Comment by kbecker87** [comment]
Hi @Pe8er, yeah, downloaded the newest release and I’m on the newest Version of Übersicht. I get those errors even if I don’t have iTunes running.

**Comment by Pe8er** [comment]
I'm so sorry, I can't help you man 😩

**Comment by kbecker87** [comment]
@Pe8er I’m guessing it has to do with my mac config then. Thanks for your effort trying to solve my problem! I’ll come back when High Sierra is released and I did an update to see if something’s changed.
